version: "3"
services:
  test:
    build: .
    ports:
      - "3600:3600"
    container_name: gfw-biomass-loss-api-test
    environment:
      NODE_ENV: test
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://biomass.default.svc.cluster.local:3600
      MICROSERVICE_TOKEN: cttoken
      PORT: 3600
      NODE_PATH: app/src
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
